version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env  # <-- Variables sensibles aquí
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: dbuser
      DB_NAME: app_db
      INIT_DB: "false"
    volumes:
      - ./:/app  # Solo la carpeta "app"
      - ./files:/app/files
    depends_on:
      db:
        condition: service_healthy  # Espera a que la DB esté lista

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:  # <-- Healthcheck agregado
      test: ["CMD-SHELL", "pg_isready -U dbuser -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: